openapi: 3.0.1
info:
  title: Gestion Ecole
  version: 0.1.0
servers:
- url: "{server}:{port}/gestionEcole"
  variables:
    port:
      default: '9090'
    server:
      default: http://localhost
paths:
  "/classe":
    get:
      summary: Get all classe
      operationId: getAllClasse
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "664c83ac531081d63bee7b2f"
                    idClasse:
                      type: string
                      example: "S001"
                    capacite:
                      type: string
                      example: "150"
                    __v:
                      type: integer
                      example: 0
